server:
  port: 8080
spring:
  cloud:
    function:
      definition: fooEventConsumer;fooEventSupplier
    schemaRegistryClient:
      endpoint: http://localhost:8081
      cached: true
    stream:
      bindings:
        fooEventSupplier-out-0:
          contentType: application/json
          destination: foo-event-topic-123
        fooEventConsumer-in-0:
          contentType: application/json
          destination: foo-event-topic-123
          group: foo
      kafka:
        binder:
          brokers: "localhost:9092"
          producer-properties:
            schema.registry.url: http://localhost:8081
          consumer-properties:
            schema.registry.url: http://localhost:8081
  kafka:
    consumer:
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer



logging:
  level:
     org.springframework: INFO
     org.hibernate.type.descriptor.sql.BasicBinder: INFO
     com.tui.schemaregistry.sample: INFO
